# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AudioSearch.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(841, 536)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("assets/ic_window_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btn_picker = QtGui.QPushButton(self.centralwidget)
        self.btn_picker.setMinimumSize(QtCore.QSize(147, 32))
        self.btn_picker.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_picker.setFocusPolicy(QtCore.Qt.TabFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("assets/ic_video.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_picker.setIcon(icon1)
        self.btn_picker.setObjectName(_fromUtf8("btn_picker"))
        self.horizontalLayout.addWidget(self.btn_picker)
        self.btn_search = QtGui.QPushButton(self.centralwidget)
        self.btn_search.setMinimumSize(QtCore.QSize(104, 32))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../ImageSearch/assets/ic_search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search.setIcon(icon2)
        self.btn_search.setObjectName(_fromUtf8("btn_search"))
        self.horizontalLayout.addWidget(self.btn_search)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBoxColorHist = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxColorHist.setEnabled(True)
        self.checkBoxColorHist.setChecked(True)
        self.checkBoxColorHist.setObjectName(_fromUtf8("checkBoxColorHist"))
        self.horizontalLayout_3.addWidget(self.checkBoxColorHist)
        self.doubleSpinBoxColorHist = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxColorHist.setDecimals(1)
        self.doubleSpinBoxColorHist.setSingleStep(0.5)
        self.doubleSpinBoxColorHist.setProperty("value", 3.0)
        self.doubleSpinBoxColorHist.setObjectName(_fromUtf8("doubleSpinBoxColorHist"))
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxColorHist)
        self.checkBoxVisualConcept = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxVisualConcept.setEnabled(True)
        self.checkBoxVisualConcept.setChecked(True)
        self.checkBoxVisualConcept.setTristate(False)
        self.checkBoxVisualConcept.setObjectName(_fromUtf8("checkBoxVisualConcept"))
        self.horizontalLayout_3.addWidget(self.checkBoxVisualConcept)
        self.doubleSpinBoxVisualConcept = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxVisualConcept.setDecimals(1)
        self.doubleSpinBoxVisualConcept.setSingleStep(0.5)
        self.doubleSpinBoxVisualConcept.setProperty("value", 2.0)
        self.doubleSpinBoxVisualConcept.setObjectName(_fromUtf8("doubleSpinBoxVisualConcept"))
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxVisualConcept)
        self.checkBoxVisualKeyword = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxVisualKeyword.setEnabled(True)
        self.checkBoxVisualKeyword.setFocusPolicy(QtCore.Qt.TabFocus)
        self.checkBoxVisualKeyword.setChecked(True)
        self.checkBoxVisualKeyword.setObjectName(_fromUtf8("checkBoxVisualKeyword"))
        self.horizontalLayout_3.addWidget(self.checkBoxVisualKeyword)
        self.doubleSpinBoxVisualKeyword = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxVisualKeyword.setDecimals(1)
        self.doubleSpinBoxVisualKeyword.setSingleStep(0.5)
        self.doubleSpinBoxVisualKeyword.setProperty("value", 1.0)
        self.doubleSpinBoxVisualKeyword.setObjectName(_fromUtf8("doubleSpinBoxVisualKeyword"))
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxVisualKeyword)
        self.checkBoxDeepLearning = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxDeepLearning.setEnabled(True)
        self.checkBoxDeepLearning.setChecked(True)
        self.checkBoxDeepLearning.setObjectName(_fromUtf8("checkBoxDeepLearning"))
        self.horizontalLayout_3.addWidget(self.checkBoxDeepLearning)
        self.doubleSpinBoxDeepLearning = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxDeepLearning.setDecimals(1)
        self.doubleSpinBoxDeepLearning.setSingleStep(0.5)
        self.doubleSpinBoxDeepLearning.setProperty("value", 3.0)
        self.doubleSpinBoxDeepLearning.setObjectName(_fromUtf8("doubleSpinBoxDeepLearning"))
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxDeepLearning)
        self.tags_search = QtGui.QLineEdit(self.centralwidget)
        self.tags_search.setObjectName(_fromUtf8("tags_search"))
        self.horizontalLayout_3.addWidget(self.tags_search)
        self.doubleSpinBoxText = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxText.setDecimals(1)
        self.doubleSpinBoxText.setSingleStep(0.5)
        self.doubleSpinBoxText.setProperty("value", 1.0)
        self.doubleSpinBoxText.setObjectName(_fromUtf8("doubleSpinBoxText"))
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxText)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.listWidgetResults = QtGui.QListWidget(self.centralwidget)
        self.listWidgetResults.setEnabled(True)
        self.listWidgetResults.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.listWidgetResults.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listWidgetResults.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listWidgetResults.setAlternatingRowColors(False)
        self.listWidgetResults.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.listWidgetResults.setIconSize(QtCore.QSize(140, 140))
        self.listWidgetResults.setResizeMode(QtGui.QListView.Adjust)
        self.listWidgetResults.setViewMode(QtGui.QListView.IconMode)
        self.listWidgetResults.setUniformItemSizes(True)
        self.listWidgetResults.setObjectName(_fromUtf8("listWidgetResults"))
        self.verticalLayout.addWidget(self.listWidgetResults)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btn_reset = QtGui.QPushButton(self.centralwidget)
        self.btn_reset.setMinimumSize(QtCore.QSize(66, 32))
        self.btn_reset.setObjectName(_fromUtf8("btn_reset"))
        self.horizontalLayout_5.addWidget(self.btn_reset)
        self.btn_quit = QtGui.QPushButton(self.centralwidget)
        self.btn_quit.setMinimumSize(QtCore.QSize(66, 32))
        self.btn_quit.setObjectName(_fromUtf8("btn_quit"))
        self.horizontalLayout_5.addWidget(self.btn_quit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 841, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.listWidgetResults.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.checkBoxVisualConcept, self.checkBoxVisualKeyword)
        MainWindow.setTabOrder(self.checkBoxVisualKeyword, self.checkBoxDeepLearning)
        MainWindow.setTabOrder(self.checkBoxDeepLearning, self.btn_reset)
        MainWindow.setTabOrder(self.btn_reset, self.btn_quit)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "CS2108 Audio Search", None))
        self.btn_picker.setText(_translate("MainWindow", "Choose Video", None))
        self.btn_search.setText(_translate("MainWindow", "Estimate Venue", None))
        self.checkBoxColorHist.setText(_translate("MainWindow", "Color Histogram", None))
        self.checkBoxVisualConcept.setText(_translate("MainWindow", "Visual Concept", None))
        self.checkBoxVisualKeyword.setText(_translate("MainWindow", "Visual Keyword", None))
        self.checkBoxDeepLearning.setText(_translate("MainWindow", "Deep Learning", None))
        self.btn_reset.setText(_translate("MainWindow", "Clear", None))
        self.btn_quit.setText(_translate("MainWindow", "Quit", None))

